### PR TITLE
Update deprecation link in README.md

### PR DESCRIPTION
**Pull request by anguillanneuf**
Closes #47

### CODE REVIEW

**Review by ace-n — APPROVED** [review]
LGTM, but I'd like @JustinBeckwith to confirm this link is correct.

**Comment by JustinBeckwith** [comment]
So LGTM because I don't know anything, and fewer repos is better than more. Only question I have (not blocking this) is if the sample belongs in App Engine specific code, or if this is a generic PubSub sample.

**Comment by anguillanneuf** [comment]
The code in `cloud-pubsub-samples-java/appengine-push` is both App Engine and Pub/Sub. Hmm, if I have to choose one, I would say it's App Engine code (showing how to integrate with Pub/Sub).

Feel free to merge because I don't have merge rights :-)

**Comment by ace-n** [comment]
@JustinBeckwith SGTM.

@anguillanneuf merging. 🙂

**Pull request merged**
