### PR TITLE
Added integration tests to cmdline-pull and the global travis config.

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by tmatsuo** [comment]
lesv@ I'd appreciate it if you could take a look!

**Comment by lesv** [comment]
k - why is there a Merge with caution! comment?

**Comment by tmatsuo** [comment]
This is because the travis build is pending.

**Comment by lesv** [comment]
LGTM - once travis completes.

**Comment by tmatsuo** [comment]
Thx, merging

**Pull request merged**
