### PR TITLE
small command line fix

### PR DESCRIPTION
**Pull request by willedwards**

### CODE REVIEW

**Comment by willedwards** [comment]
Hmm, this is a change in the README file, and the build is failing. I'd suggest the build IS failing.

**Comment by tmatsuo** [comment]
Thanks @willedwards 

Can you go https://cla.developers.google.com/clas and sign the Google Corporate CLA?

**Comment by tmatsuo** [comment]
Re: build

This is because the test needs a secret and the secret is not available for PRs from other repos. Don't worry about it.

**Comment by tmatsuo** [comment]
Thanks for signing the CLA, merging

**Pull request merged**
